services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5001:5001"
    environment:
      FLASK_DEBUG: "1"  # Enable Flask debug mode
      POSTGRES_HOST: db
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    depends_on:
      - db
    volumes:
      - .:/app  # allow live code updates
    networks:
      - flasknet

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flasknet

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - flasknet

volumes:
  pgdata:

networks:
  flasknet:
    driver: bridge
